---
name: CI
on:
  push:
jobs:
  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Composer dependencies"
        run: "composer ci:install"
      - name: "Run command"
        run: "composer ci:php:stan"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    needs: [ code-quality ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Composer dependencies"
        run: "composer ci:install"
      - name: "Run the tests"
        run: "composer ci:tests:unit"

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-22.04
    needs: [ code-quality ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Composer dependencies"
        run: "composer update --no-progress"
      - name: "Run the tests"
        run: "composer ci:tests:functional"
